services:
  backend:
    build: ./POCKET  # ✅ Backend (Django) için Dockerfile burada
    container_name: pocket_backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # ✅ MySQL tamamen hazır olduğunda başlat
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DATABASE_URL=mysql://pocket_user:pocket_password@db/pocket_db
    command: >
      sh -c "python manage.py migrate &&
         python manage.py collectstatic --noinput &&
         python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./POCKET:/app  # ✅ Django kodları için volume (Canlı güncellemeler için)

  db:
    image: mysql:8.0
    container_name: pocket_db
    restart: always
    environment:
      MYSQL_DATABASE: pocket_db
      MYSQL_USER: pocket_user
      MYSQL_PASSWORD: pocket_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    healthcheck:  # ✅ Sağlık kontrolü ekledik
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
    volumes:
      - pocket_mysql_data:/var/lib/mysql  # ✅ Database için volume

  nginx:
    build: ./nginx
    container_name: pocket_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - backend_static:/app/static

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db

volumes:
  pocket_mysql_data:
  backend_static:
