# Generated by Django 5.1.6 on 2025-04-01 07:29

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BenutzerProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_bild', models.ImageField(blank=True, null=True, upload_to='profil_bilder/')),
                ('benutzer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBenutzerProfil',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('profil_bild', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('benutzer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical benutzer profil',
                'verbose_name_plural': 'historical benutzer profils',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=50)),
                ('nachname', models.CharField(max_length=50)),
                ('standort', models.CharField(max_length=100)),
                ('erste_taetigkeitsstaette', models.CharField(max_length=150)),
                ('status', models.CharField(blank=True, choices=[('-', 'Bitte wählen'), ('intern', 'Intern'), ('freelancer', 'Freelancer')], default='-', max_length=10)),
                ('abteilung', models.CharField(max_length=100)),
                ('rolle', models.CharField(blank=True, choices=[('-', 'Bitte wählen'), ('Manager', 'Manager'), ('Mitarbeiter', 'Mitarbeiter')], default='-', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mitarbeiter',
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projektname', models.CharField(max_length=100)),
                ('startdatum', models.DateField()),
                ('enddatum', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kunde_1', models.CharField(max_length=100)),
                ('kunde_2', models.CharField(blank=True, max_length=100, null=True)),
                ('projekttyp', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('-', 'Bitte wählen'), ('geplant', 'Geplant'), ('laufend', 'Laufend'), ('abgeschlossen', 'Abgeschlossen')], default='-', max_length=20)),
                ('beschreibung', models.TextField()),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellt_projekte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projekte',
            },
        ),
        migrations.CreateModel(
            name='Einnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zahlungseingang', models.DateField(blank=True, null=True)),
                ('zahlungsart', models.CharField(max_length=50)),
                ('rechnungsnummer', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('-', 'Bitte wählen'), ('geplant', 'Geplant'), ('offen', 'Offen'), ('verrechnet', 'Verrechnet')], default='-', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellt_einnahmen', to=settings.AUTH_USER_MODEL)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projekt')),
            ],
            options={
                'verbose_name_plural': 'Einnahmen',
            },
        ),
        migrations.CreateModel(
            name='Abrechnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monat', models.CharField(help_text='Format: YYYY-MM (z.B. 2025-03)', max_length=7)),
                ('stunden', models.IntegerField()),
                ('stundensatz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('netto_summe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brutto_summe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rechnung_status', models.CharField(choices=[('-', 'Bitte wählen'), ('nicht erstellt', 'Nicht erstellt'), ('erstellt', 'Erstellt'), ('gesendet', 'Gesendet'), ('erhalten', 'Erhalten'), ('storniert', 'Storniert')], default='-', max_length=20)),
                ('zahlungseingang', models.DateField(blank=True, null=True)),
                ('leistungsnachweis', models.CharField(blank=True, max_length=100, null=True)),
                ('bemerkung', models.TextField(blank=True, null=True)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mitarbeiter')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projekt')),
            ],
            options={
                'verbose_name_plural': 'Abrechnungen',
            },
        ),
        migrations.CreateModel(
            name='Abordnung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitraum_start', models.DateField()),
                ('zeitraum_ende', models.DateField()),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mitarbeiter')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projekt')),
            ],
            options={
                'verbose_name_plural': 'Abordnungen',
            },
        ),
        migrations.CreateModel(
            name='ProjektMitarbeiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mitarbeiter')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projekt')),
            ],
            options={
                'verbose_name_plural': 'ProjektMitarbeiter',
            },
        ),
        migrations.CreateModel(
            name='Reisebericht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('zielort', models.CharField(max_length=100)),
                ('zweck', models.TextField()),
                ('verkehrsmittel', models.CharField(max_length=50)),
                ('distanz_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kosten_fahrt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kosten_übernachtung', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gesamtkosten', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rechnung_vorhanden', models.CharField(choices=[('-', 'Bitte wählen'), ('Ja', 'Ja'), ('Nein', 'Nein')], default='-', max_length=10)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mitarbeiter')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projekt')),
            ],
            options={
                'verbose_name_plural': 'Reiseberichte',
            },
        ),
        migrations.CreateModel(
            name='Schulungskosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schulungstyp', models.CharField(max_length=100)),
                ('datum_start', models.DateField()),
                ('datum_ende', models.DateField()),
                ('dauer', models.IntegerField()),
                ('kosten', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anbieter', models.CharField(max_length=150)),
                ('teilgenommen', models.CharField(choices=[('-', 'Bitte wählen'), ('Ja', 'Ja'), ('Nein', 'Nein')], default='-', max_length=10)),
                ('beschreibung', models.TextField(blank=True, null=True)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mitarbeiter')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projekt')),
            ],
            options={
                'verbose_name_plural': 'Schulungskosten',
            },
        ),
    ]
