# Generated by Django 5.1.7 on 2025-04-01 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='manager',
            field=models.ManyToManyField(blank=True, related_name='verwaltet_projekte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='erstellt_von',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='erstellt_projekte', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
