# Generated by Django 5.1.6 on 2025-03-31 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Einnahme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zahlungseingang', models.DateField(blank=True, null=True)),
                ('zahlungsart', models.CharField(max_length=50)),
                ('rechnungsnummer', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('-', 'Bitte wählen'), ('geplant', 'Geplant'), ('offen', 'Offen'), ('verrechnet', 'Verrechnet')], default='-', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellt_einnahmen', to=settings.AUTH_USER_MODEL)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projekt')),
            ],
        ),
    ]
