# Generated by Django 5.2 on 2025-04-04 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projekt_manager_alter_projekt_erstellt_von'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrechnung',
            name='mitarbeiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mitarbeiter'),
        ),
        migrations.AlterField(
            model_name='abrechnung',
            name='projekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abrechnungen', to='core.projekt'),
        ),
        migrations.AlterField(
            model_name='einnahme',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einnahmen', to='core.projekt'),
        ),
        migrations.AlterField(
            model_name='reisebericht',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reiseberichte', to='core.projekt'),
        ),
        migrations.AlterField(
            model_name='schulungskosten',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schulungskosten', to='core.projekt'),
        ),
    ]
