# Generated by Django 5.1.6 on 2025-03-31 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_einnahme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='einnahme',
            options={'verbose_name_plural': 'Einnahmen'},
        ),
    ]
