# Generated by Django 5.2 on 2025-04-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_abrechnung_mitarbeiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abrechnung',
            name='mitarbeiter',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.mitarbeiter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abrechnung',
            name='projekt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='abrechnungen', to='core.projekt'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='status',
            field=models.CharField(choices=[('-', 'Bitte wählen'), ('intern', 'Intern'), ('freelancer', 'Freelancer')], default='-', max_length=10),
        ),
    ]
